### ISSUE TITLE
Exception while saving a file with Download() method

### ISSUE THREAD

**Issue by jshvlv** [selenide/selenide-selenoid#14]
**Versions: **
selenide-selenoid 2.2.2
selenide 6.5.0

**If test clicks to  `<a href=..>` element - file is downloaded successully:**
```
2022-05-23 10:01:10 INFO  DownloadFileToFolder:119 - Downloaded 1 files:
  #1  D:\Work\Projects\pir_new\target\download\1653289158085_5992_1\РП ПИР.zip

2022-05-23 10:01:10 INFO  FileHelper:46 - Creating folder: D:\Work\Projects\pir_new\target\download\95a036ee-5376-41b1-87b6-df5e3c25001a
2022-05-23 10:01:10 INFO  WebActionWebSteps:73 - Файл загружен 'D:\Work\Projects\pir_new\target\download\95a036ee-5376-41b1-87b6-df5e3c25001a\РП ПИР.zip'
```

**But if test clicks to a button without href etc, backend generate file and file downloads not successful:**

**Stacktrace:**
```
2022-05-23 09:48:34 INFO  DownloadFileToFolder:119 - Downloaded 1 files:
  #1  D:\Work\Projects\pir_new\target\download\1653288261666_9724_1\8a9330b8-4a6a-4d6f-bb66-2905783f8635.tmp

2022-05-23 09:48:34 INFO  FileHelper:46 - Creating folder: D:\Work\Projects\pir_new\target\download\a192c8cb-68c4-406d-8860-84be728df20c

Step failed
java.lang.IllegalStateException: Failed to move file D:\Work\Projects\pir_new\target\download\1653288261666_9724_1\8a9330b8-4a6a-4d6f-bb66-2905783f8635.tmp to D:\Work\Projects\pir_new\target\download\a192c8cb-68c4-406d-8860-84be728df20c\8a9330b8-4a6a-4d6f-bb66-2905783f8635.tmp (files in D:\Work\Projects\pir_new\target\download\1653288261666_9724_1: [Не подтвержден 18385.crdownload])
	at com.codeborne.selenide.impl.FileHelper.moveFile(FileHelper.java:63)
	at com.codeborne.selenide.impl.DownloadFileToFolder.archiveFile(DownloadFileToFolder.java:140)
	at com.codeborne.selenide.impl.DownloadFileToFolder.clickAndWaitForNewFilesInDownloadsFolder(DownloadFileToFolder.java:88)
	at com.codeborne.selenide.impl.DownloadFileToFolder.lambda$download$0(DownloadFileToFolder.java:57)
	at com.codeborne.selenide.impl.WindowsCloser.runAndCloseArisedWindows(WindowsCloser.java:25)
	at com.codeborne.selenide.impl.DownloadFileToFolder.download(DownloadFileToFolder.java:56)
	at org.selenide.selenoid.DownloadFileInSelenoid.download(DownloadFileInSelenoid.java:54)
	at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:64)
	at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:27)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:155)
	at ru.lanit.at.utils.selenide.extensions.CustomCommands.execute(CustomCommands.java:19)
	at ru.lanit.at.steps.web.WebActionWebSteps.clickOnElementWithDownload(WebActionWebSteps.java:71)
	at ✽.кликнуть на кнопку "Заявка на формирование заявления в суд > Кнопка Сформировать" для загрузки файла(file:///D:/Work/Projects/pir_new/src/test/resources/features/web/settings/Test%20case%20C1349.feature:32)
Caused by: java.io.FileNotFoundException: Source 'D:\Work\Projects\pir_new\target\download\1653288261666_9724_1\8a9330b8-4a6a-4d6f-bb66-2905783f8635.tmp' does not exist
	at org.apache.commons.io.FileUtils.validateMoveParameters(FileUtils.java:3124)
	at com.codeborne.selenide.impl.FileHelper.moveFile(FileHelper.java:58)
	at com.codeborne.selenide.impl.DownloadFileToFolder.archiveFile(DownloadFileToFolder.java:140)
	at com.codeborne.selenide.impl.DownloadFileToFolder.clickAndWaitForNewFilesInDownloadsFolder(DownloadFileToFolder.java:88)
	at com.codeborne.selenide.impl.DownloadFileToFolder.lambda$download$0(DownloadFileToFolder.java:57)
	at com.codeborne.selenide.impl.DownloadFileToFolder.download(DownloadFileToFolder.java:56)
	at org.selenide.selenoid.DownloadFileInSelenoid.download(DownloadFileInSelenoid.java:54)
	at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:64)
	at com.codeborne.selenide.commands.DownloadFile.execute(DownloadFile.java:27)
	at ru.lanit.at.utils.selenide.extensions.CustomCommands.execute(CustomCommands.java:19)
```

Method:
```java
        try {
            File file = element.download(300000);
            getStorage().put("CURRENT_FILE", file);
            LOGGER.info("Файл загружен '{}'", file.toPath());
            WebChecks.waitForLoader();
        } catch (FileNotFoundException e){
            e.printStackTrace();
        }
```

**Comment by asolntsev** [comment]
@jshvlv 
1. Do I  correctly understand that you didn't really use Selenoid in this case?
At least I see from your stacktrace that `Configuration.remote` is `null`.

2.  Replace `element.download(300000);` by `element.download(300000, withExtension("zip"));`

P.S. Remove try/catch from your test. Catch is almost never needed. If you get `FileNotFoundException` - let the test fail with this exception.

**Comment by jshvlv** [comment]
Yeah it seems work! Thanks a lot!
